model:
  clip_model_path: /home/mengqing/usr/motion-diffusion-model/save/finetune_clip_all__layers/model000450000.pt ## 这个全finetune的是loss最小的，就先用这个
  # clip_model_path: save/finetune_clip_use_multiview/model000450000.pt ## 这个是multiview的权重
  clip_use_sen_emb: True  ## 这个加了发现是很有用的，之后就用这个True
  clip_use_text_token_emb: True
  use_avg_clip_model: True
  use_contronet_injection: True ## 这个置为True时，目前代码中arch一定得是encoder，decoder就不支持，也没有必要用controlnet注入
  # MDM_model_file: mdm_add_embed_motion
  MDM_model_file: mdm


training:
  use_gt_MB_simplified_data: false  ## 这个是是否直接使用gt的motion token来跑
  use_multiview_training: False ## 现在是直接使用multiview trained CLIP，这个参数好像就没什么用了
  split_info_injection: False ## 如果这个为False，下面的那个split_info_version参数就不会被用到
  split_info_version: 2

data:
  MB_simplified_data_path: /data/mengqing/HumanML3D_MB_rep_new  ## 这个参数和上面的额use_gt_MB_simplified_data有关系，为False则不会使用
  Temperal_further_pooling: false
  Joint_further_pooling: false

overwrite_config: False  ## 一般情况下默认为False，只有resume training的时候才会变成True
